<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Conteo privado elecciones seccionales 2019">
    <meta name="author" content="ceortega">
    <link rel="icon" href="./ballot-1294935_640.png">

    <title>Elecciones-2019</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="./css/sticky-footer-navbar.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
      <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?php echo Utils::createLink('home'); ?>">Elecciones 2019</a>          
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="<?php echo Utils::createLink('home'); ?>">Inicio</a></li>
            <!--<li><a href="#">Contact</a></li>-->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Registro&nbsp;<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="<?php echo Utils::createLink('new-acta', array('tipo'=>'PR')); ?>">Acta prefectos</a></li>
                <li><a href="<?php echo Utils::createLink('new-acta', array('tipo'=>'AL')); ?>">Acta alcaldes</a></li>
                <li><a href="<?php echo Utils::createLink('new-acta-p'); ?>">Acta concejales urbanos</a></li>
                <li><a href="<?php echo Utils::createLink('new-acta-pb', array('dis'=>'R')); ?>">Acta concejales rurales</a></li>
              </ul>
            </li>
            <?php if ($_SESSION['userrole']=='boss'): ?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dashboard&nbsp;<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="<?php echo Utils::createLink('stats-uni', array('tipo'=>'pr')); ?>">Acta prefectos</a></li>
                <li><a href="<?php echo Utils::createLink('stats-uni', array('tipo'=>'al')); ?>">Acta alcaldes</a></li>
                <li><a href="<?php echo Utils::createLink('stats-cu', array('dist'=>'1')); ?>">Concejales(D1)</a></li>
                <li><a href="<?php echo Utils::createLink('stats-cu', array('dist'=>'2')); ?>">Concejales(D2)</a></li>
                <li><a href="<?php echo Utils::createLink('stats-cr'); ?>">C. Rurales</a></li>
                <li><a href="<?php echo Utils::createLink('dashboard', array('pagn'=>1)); ?>">Listado de actas</a></li>
              </ul>
            </li>
            <?php endif; ?>
            <!--li><a href="#">Ayuda</a></li-->
            <li><a href="<?php echo Utils::createLink('logout'); ?>">Salir</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- Begin page content -->
    <div class="container">
      <?php if ($flashes): ?>
          <ul id="flashes">
          <?php foreach ($flashes as $flash): ?>
              <li><?php echo $flash; ?></li>
          <?php endforeach; ?>
          </ul>
      <?php endif; ?>        
      <?php require $template; ?>
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted"><a href="https://codibros.com"><img alt="Brand" src="./cb_favicon.png">&nbsp;CodiBros team</a>, 2019 &copy; Copyright Codibros corp., All rights reserved.</p>
      </div>
    </footer>    
  </body>
</html>
