<div class="page-header">
    <h3>Lista de actas registradas</h3>
</div>
<?php if (isset($invalidrole) && $invalidrole <> ''): ?>
    <div class="alert alert-danger" role="alert"><?php echo $invalidrole; ?></div>
<?php elseif (empty($records)): ?>
    <div class="alert alert-warning" role="alert">No hay registros.</div>
<?php else: ?>
  <form class="form-inline" method="post">
      <div class="form-group">
          <label for="sel1">TIPO CANDIDATO:</label>
          <select class="form-control" id="sel1" name="tipo">
              <option value="AL" <?php if(filter_has_var(INPUT_POST, 'tipo') && filter_input(INPUT_POST, 'tipo')==='AL'): echo 'selected'; endif; ?>>Alcaldes</option>
              <option value="PR" <?php if(filter_has_var(INPUT_POST, 'tipo') && filter_input(INPUT_POST, 'tipo')==='PR'): echo 'selected'; endif; ?>>Prefectos</option>
              <option value="CU" <?php if(filter_has_var(INPUT_POST, 'tipo') && filter_input(INPUT_POST, 'tipo')==='CU'): echo 'selected'; endif; ?>>Concejales urbanos</option>
              <option value="CR" <?php if(filter_has_var(INPUT_POST, 'tipo') && filter_input(INPUT_POST, 'tipo')==='CR'): echo 'selected'; endif; ?>>Concejales rurales</option>
          </select>
      </div>
      <div class="form-group">
          <label for="sel2">VALIDEZ:</label>
          <select class="form-control" id="sel2" name="escorrecta">
            <option value="T" <?php if(filter_has_var(INPUT_POST, 'escorrecta') && filter_input(INPUT_POST, 'escorrecta')==='T'): echo 'selected'; endif; ?>>Todo</option>
            <option value="N" <?php if(filter_has_var(INPUT_POST, 'escorrecta') && filter_input(INPUT_POST, 'escorrecta')==='N'): echo 'selected'; endif; ?>>Observadas</option>
            <option value="S" <?php if(filter_has_var(INPUT_POST, 'escorrecta') && filter_input(INPUT_POST, 'escorrecta')==='S'): echo 'selected'; endif; ?>>Solo válidas</option>
          </select>
      </div>
      <div class="form-group">
          <label for="sel3">USUARIO:</label>
          <select class="form-control" id="sel3" name="username">
            <option value="T">Todo</option>
            <?php foreach($usuarios as $user): ?>
            <option <?php if(filter_has_var(INPUT_POST, 'username') && filter_input(INPUT_POST, 'username')===$user['username']): echo 'selected'; endif; ?>><?=$user['username']?></option>
            <?php endforeach;?>
          </select>
      </div>
      <button type="submit" class="btn btn-default">Consultar</button>
    </form>    
    <div class="panel panel-default">
        <div class="panel-heading">ACTAS REGISTRADAS AL MOMENTO</div>
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>NUMERO</th>
                    <th>TIPO</th>
                    <th>T. FIRMAS</th>
                    <th>V. BLANCOS</th>
                    <th>V. NULOS</th>
                    <th>USUARIO</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($records as $acta): ?>
                    <tr>
                        <td><?= $acta['numero'] ?></td>
                        <td><?= $acta['tipo'] ?></td>
                        <td><?= $acta['tfirmas'] ?></td>
                        <td><?= $acta['votosblancos'] ?></td>
                        <td><?= $acta['votosnulos'] ?></td>
                        <td><?= $acta['username'] ?></td>
                        <?php if ($acta['escorrecta']==='S'): ?>
                            <td><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></td>
                        <?php else: ?>
                            <td><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span></td>
                        <?php endif; ?>
                        <?php if (in_array($acta['tipo'], ['AL', 'PR'])): ?>
                            <td><a href="<?= Utils::createLink('view-acta', array('id' => $acta['idacta'])); ?>">Abrir</a></td>
                        <?php else: ?>
                            <td><a href="<?= Utils::createLink('view-acta-p', array('id' => $acta['idacta'])); ?>">Abrir</a></td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>    
    </div>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li>
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <?php for ($i = $pagn; $i <= $total_pages; $i++): ?>
                <li><a href="<?php echo Utils::createLink('dashboard', array('pagn' => $i)); ?>"><?= $i ?></a></li>
            <?php endfor; ?>
            <li>
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
<?php endif; ?>