<h1>¡Bienvenido <mark><?=Utils::getUsername();?></mark>!</h1>

<p class="p">Bienvenido al portal de control privado de votos de - <b>ELECCIONES SECCIONALES 2019</b>.</p>
<ul class="p">
    Este portal tiene las siguientes funcionalidades:    
    <li>Registro de actas unipersonales para candidatos a ALCALDES y PREFECTOS</li>
    <li>Registro de actas pluripersonales para candidatos a CONCEJALES</li>
    <li>Visulización individual de actas</li>
    <li>Listado de actas registradas por usuario</li>
    <li>Estadísticas del proceso</li>    
    <li>Controla el acceso no autorizado</li>
</ul>
<!--<p class="p">Detailed information can be found in the <i>readme.html</i> file (in project directory).</p>
<p class="p"><b>This sample is not intented to be used on a production server without any changes.</b></p>-->
