<?php if (empty($listas)): ?>
    <p>No LISTAS items found.</p>
<?php else: ?>
<script src="../web/js/actap.js"></script>
<div class="page-header">
  <h3>ACTA VOTACION CONCEJALES (<?= $tipo;?>)</h3>
  <?php if (isset($yaexiste)): ?>
  <div class="alert alert-warning">
    <strong>¡Advertencia!</strong>&nbsp;<?= sprintf('El acta número %s ya se encuentra registrada por favor revisar. ', $_POST['numero']); ?>
  </div>
  <?php endif; ?>
</div>
    <form class="form-horizontal" method="post" name="detalle">
      <input type="hidden" name="tipocandidato" value="<?= $search->getTipo(); ?>">
        <div class="form-group">
            <label for="numero" class="col-sm-10 control-label">NUMERO DE ACTA</label>
            <div class="col-sm-2">
                <input type="text" class="form-control" id="numero" placeholder="" name="numero" min="0" required>
            </div>
        </div>
        <div class="form-group">
            <label for="total" class="col-sm-10 control-label">TOTAL FIRMAS Y HUELLAS DACTILARES QUE CONSTAN EN EL PADRÓN ELECTORAL</label>
          <div class="col-sm-2">
            <input type="number" class="form-control" id="total" placeholder="" name="total" min="0" max="9999" required>
          </div>
        </div>
        <div class="form-group">
            <label for="blancos" class="col-sm-10 control-label">VOTOS BLANCOS</label>
            <div class="col-sm-2">
              <input type="number" class="form-control" id="blancos" placeholder="" name="blancos" min="0" max="9999">
            </div>
        </div>
        <div class="form-group">
            <label for="nulos" class="col-sm-10 control-label">VOTOS NULOS</label>
            <div class="col-sm-2">
              <input type="number" class="form-control" id="nulos" placeholder="" name="nulos" min="0" max="9999">
            </div>
        </div>
        <?php foreach ($listas as $lista): ?>
            <div class="panel panel-default">
              <div class="panel-heading">VOTACION OBTENIDA POR LOS CANDIDATOS DE LA LISTA&nbsp;<?= $lista['codigolista']; ?></div>
              <table class="table table-condensed">
                <thead>
                  <tr>
                    <th class="col-sm-1 text-center">ORD.</th>
                    <th class="col-sm-5 text-justify">CANDIDATOS</th>
                    <th class="col-sm-2 text-center">NOMINALES</th>
                    <th class="col-sm-2 text-center">LISTA</th>
                    <th class="col-sm-2 text-center">TOTAL</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach ($lista['candidatos'] as $candidato): ?>
                  <tr>
                    <td class="text-center"><?= $candidato['ordenpapeleta']; ?></td>
                    <td class="text-justify"><?= utf8_encode($candidato['nombre']); ?></td>
                    <td><input type="number" class="form-control vn <?=$lista['codigolista'];?>" name="<?= 'vn_'.$candidato['idcandidato']; ?>" tabindex="-1" readonly></td>
                    <td><input type="number" class="form-control vl <?=$lista['codigolista'];?>" name="<?= 'vl_'.$candidato['idcandidato']; ?>" tabindex="-1" readonly></td>
                    <td><input type="number" class="form-control suma <?=$lista['codigolista'];?>" id="<?= 'suma_'.$candidato['idcandidato']; ?>" min="0" max="9999"></td>
                  </tr>
                  <?php endforeach; ?>
                  <tr>
                    <td colspan=4>&nbsp;</td>
                    <td><button type="button" id="asd" class="btn btn-default" onclick="calcular('<?=$lista['codigolista'];?>');">Calcular</button></td>
                  </tr>
                </tbody>
              </table>
            </div>
      <?php endforeach; ?>
      <button type="submit" class="btn btn-primary">Registrar</button>
    </form>
<?php endif; ?>
